apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralbank-image
  labels:
    app: neuralbank-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-image
  template:
    metadata:
      labels:
        app: neuralbank-image
    spec:
      containers:
        - name: neuralbank-image
          image: ghcr.io/KillahBlitz/NeuralBank:latest
          command: ["python", "src/tasks/image_event_handler.py"]
          envFrom:
            - secretRef:
                name: neuralbank-env
          imagePullPolicy: Alway