apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralbank-extractor
  labels:
    app: neuralbank-extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-extractor
  template:
    metadata:
      labels:
        app: neuralbank-extractor
    spec:
      containers:
        - name: neuralbank-extractor
          image: ghcr.io/<OWNER>/neuralbank:latest
          command: ["python", "src/tasks/extraction_event_handler.py"]
          envFrom:
            - secretRef:
                name: neuralbank-env
          imagePullPolicy: Always