apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralbank-producer
  labels:
    app: neuralbank-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-producer
  template:
    metadata:
      labels:
        app: neuralbank-producer
    spec:
      containers:
        - name: neuralbank-producer
          image: ghcr.io/<OWNER>/neuralbank:latest
          command: ["python", "src/tasks/event_producer.py"]
          envFrom:
            - secretRef:
                name: neuralbank-env
          imagePullPolicy: Always